apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: my-app-production
    namespace: argocd
spec:
    project: default
    source:
        repoURL: "git@github.com:lakunzy7/config-repo-payday.git" # Replace with your config repo URL
        path: apps/my-app/overlays/production
        targetRevision: HEAD
    destination:
        server: "https://kubernetes.default.svc"
        namespace: production
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
